### ISSUE TITLE
slug page 

### ISSUE THREAD

**Issue by rjcrystal** [mihneadb/no-nonsense#11] opened 2015-02-08 17:36 UTC
slug page is not formed correctly check here http://blog.scaps.me/author/rjcrystal/

**Comment by mihneadb** [comment] 2015-02-08 19:16
Hi,

Could you please provide more details? I don't understand what the problem is.


Thanks!

**Comment by rjcrystal** [comment] 2015-02-10 19:53
yes i've installed your theme on my server at blog.scaps.me and the slug page error is on this page blog.scaps.me/author/rjcrystal

**Comment by mihneadb** [comment] 2015-02-10 20:45
Ohh, now I understand. You mean the author page that Ghost has added. Yes, the theme does not currently support this, which is why there is no link that leads to the /author/author-slug page.

I've opened https://github.com/mihneadb/no-nonsense/issues/12 to fix this, however I cannot make a promise on a timeline for it. However, contributions are welcome! :)

**Comment by rjcrystal** [comment] 2015-02-11 03:08
thanks man :+1:  i'm trying to learn ghost maybe i can help

**Comment by mihneadb** [comment] 2015-02-19 18:58
@rjcrystal this was fixed in #16, make sure to get the latest version.

**Closed by mihneadb** 2015-02-19 18:58 UTC

**Comment by rjcrystal** [comment] 2015-02-19 19:48
yea got it now looks awesome in the screenshots.
